### PR TITLE
User can edit username and password

### PR DESCRIPTION
**Pull request by aboubacar108**
## Description

Users are now able to edit their username and password in their profile.
## Related Issue

JIRA BP-32

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Review by mautoranzo — DISMISSED** [review]
I am receiving this when I try to run the server:

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

**Comment by mautoranzo** [comment]
Never mind, was just the .env that was not there when I move to your branch. But I realized that you didn't do a merge of dev before of your pull request, please check that.

**Comment by aboubacar108** [comment]
@mautoranzo Hey Mau, I just did the merge of dev.

**Review by frankstepanski — APPROVED** [review]
Nice job.

**Comment by mautoranzo** [comment]
Nice, thank you Abou

**Review by alejandroo-pc — APPROVED** [review]
looks good

**Review by alejandroo-pc — APPROVED** [review]

**Pull request merged**
